# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 19 Dec 2015 05:44:37 +0000
*               @ALL          0
*               @user         8
